language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - test -f requirements.txt && pip install -r requirements.txt
  - test -f dev-requirements.txt && pip install -r dev-requirements.txt
  - python setup.py install

script:
  - python tests/test.py
